package com.nupuit.nupuitcontactlist.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CONTACTS".
 */
@Entity
public class Contacts {

    @Id(autoincrement = true)
    private Long id;
    private String contact_id;
    private String name;
    private String number;
    private String uri;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Contacts() {
    }

    public Contacts(Long id) {
        this.id = id;
    }

    @Generated
    public Contacts(Long id, String contact_id, String name, String number, String uri) {
        this.id = id;
        this.contact_id = contact_id;
        this.name = name;
        this.number = number;
        this.uri = uri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getContact_id() {
        return contact_id;
    }

    public void setContact_id(String contact_id) {
        this.contact_id = contact_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

    public String getUri() {
        return uri;
    }

    public void setUri(String uri) {
        this.uri = uri;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
